// ------------------------------------- ELECTRICAL ENGINEERING DATA -------------------------------------
// PSS ACTIVITY DATA
List activity_data = [
  "Unpacking of PSS at site",
  "Check for Physical Damage ",
  "Check for Outage Gadgets like LED Indication , Meter,switch, Handle",
  "Check for Record of PSS  Sr No, Make and year of Manufacturing",
  "Check for  Oil  leakage for Transformer.",
  "Check the PSS foundation as per approved  drawing.",
  "Lifting / shifting of PSS as per OEM Guideline to avoid Damage",
  "Install the PSS on foundation with the help of crane or shift it manually on the foundation if crane approach is not availabl(Indoor). Ensure that the RMU / LTP sides are as per approved drawing.",
  "Position PSS as per the drawing for clearances.",
  "Fix the anchor points with anchor fasteners",
  "Earth pit preparation and Testing of Earth pit and Record the value",
  "Identification & Nomenclature of PSS Earth pit ",
  "Connect earth bus for RMU/LT at two points with 50x6 mm GI strip (one with grid & other directly to earth pit). ",
  "Connect earth bus for Transformer Neutral Earthing at two points with 2x50x6 mm GI strip (directly to earth pit). ",
  "Connect earth bus for Transformer Body at two points with 2x50x6 mm GI strip (directly to earth pit). • Ensure use of M12 nut bolt with two flat doller washers",
  "Tightness check for all the component of PSS Like Transformer Bushing, Busbar, LT switchgear ,Power/Control circuit, connected HT/LT Power cable.",
  "Ensure PSS LT Cable Laying as per Approved drawing ",
  "Installation of  HT/LT Insulation  mat as per IEC standard",
  "Ensuring Cable tagging and Nomenclature  of source, Outgoing feeder and PSS Marking",
  "Ensuring  Availability of Fire fighting equipment as per Safety Regulation.",
  "Check for Vermin  Proofing and Opening to be close.",
  "Ensure Housekeeping of PSS Internal and External Area",
  "Clear the equipment for Testing"
];

// RMU ACTIVITY DATA
List rmu_activity_data = [
  "Unpacking of RMU at site",
  "Check for Physical Damage ",
  "Check for Outage Gadgets like LED Indication , Meter,switch, Handle",
  "Check for Record of RMU  Sr No, Make and year of Manufacturing",
  "Check the RMU foundation as per approved  drawing.",
  "Lifting / shifting of RMU as per OEM Guideline to avoid Damage",
  "Install the RMU on foundation with the help of crane or shift it manually on the foundation if crane approach is not available (Indoor). Ensure that the RMU / LTP sides are as per approved drawing.",
  "Position RMU as per the drawing for clearances .",
  "Fix the anchor points with anchor fasteners",
  "Earth pit preparation and Testing of Earth pit and Record the value",
  "Identification & Nomenclature of RMU Earth pit ",
  "Connect earth bus for RMU/LT at two points with 50x6 mm GI strip (one with grid & other directly to earth pit). ",
  "Tightness check for all the component of RMU Like Bushing, Busbar,Power/Control circuit, connected HT Power cable.",
  "Make sure the trench/openings provided for HT cable entries match with bottom of gland plate for same.",
  "Lay and connect the control cables as per ICS.",
  "Installation of  HT/LT Insulation  mat as per IEC standard",
  "Ensuring Cable tagging and Nomenclature  of source, Outgoing feeder and RMU Marking",
  "Ensuring  Availability of Fire fighting equipment as per Safety Regulation.",
  "Check for Vermin  Proofing and Opening to be close.",
  "Ensure Housekeeping of RMU Internal and External Area",
  "Clear the equipment for Testing",
];
// CT ACTIVITY DATA
List ct_activity_data = [
  "Unpacking of Conventional Transformer at site",
  "Check for Physical Damage ",
  "Check for Outage Gadgets like LED Indication , Meter,switch, Handle",
  "Check for Record of Conventional Transformer Sr No, Make and year of Manufacturing",
  "Check for  Oil  leakage for Transformer.",
  "Check the Conventional Transformer foundation as per approved  drawing.",
  "Lifting / shifting of Conventional Transformer as per OEM Guideline to avoid Damage",
  "Install the Conventional Transformer on foundation with the help of crane or shift it manually on the foundation if crane approach is not available (Indoor). Ensure that the Conventional Transformer / LTP sides are as per approved drawing.",
  "Position Conventional Transformer as per the drawing for clearances .",
  "Fix the anchor points with anchor fasteners",
  "Earth pit preparation and Testing of Earth pit and Record the value",
  "Identification & Nomenclature of Conventional Transformer Earth pit ",
  "Connect earth bus for RMU/LT at two points with 50x6 mm GI strip (one with grid & other directly to earth pit). ",
  "Connect earth bus for Transformer Neutral Earthing at two points with 2x50x6 mm GI strip (directly to earth pit). ",
  "Connect earth bus for Transformer Body at two points with 2x50x6 mm GI strip (directly to earth pit).",
  "Tightness check for all the component of Conventional  Like Transformer Bushing, Busbar, LT switchgear ,Power/Control circuit, connected HT/LT Power cable.",
  "Installation of  HT/LT Insulation  mat as per IEC standard",
  "Ensuring Cable tagging and Nomenclature  of source, Outgoing feeder and Conventional Transformer Marking",
  "Ensuring  Availability of Fire fighting equipment as per Safety Regulation.",
  "Check for Vermin  Proofing and Opening to be close.",
  "Ensure Housekeeping of Conventional Transformer External Area",
  "Clear the equipment for Testing",
];
// CMU ACTIVITY DATA
List cmu_activity_data = [
  "Unpacking of CT PT Metering Panel at site",
  "Check for Physical Damage ",
  "Check for Outage Gadgets like LED Indication , Meter,switch, Handle",
  "Check for Record ofCT PT Metering Panel Sr No, Make and year of Manufacturing",
  "Check the CT PT Metering Panel foundation as per approved  drawing.",
  "Lifting / shifting of CT PT Metering Panel as per OEM Guideline to avoid Damage",
  "Install the CT PT Metering Panel on foundation with the help of crane or shift it manually on the foundation if crane approach is not available (Indoor). Ensure that the CT PT Metering Panel sides are as per approved drawing.",
  "Check level of the entire channel/base frame provided for CT PT Metering Panel before installation	",
  "Position CT PT Metering Panel as per the drawing for clearances .",
  "Fix the anchor points with anchor fasteners",
  "Earth pit preparation and Testing of Earth pit and Record the value for CT PT Metering Panel",
  "Provide earthing from two different earthing grids to panels by 50x6 GI. Busbar.",
  "Identification & Nomenclature of CT PT Metering Panel Earth pit ",
  "Tightness check for all the component of CT PT Metering Panel Like Busbar,Power/Control circuit,All Installed Component",
  "Ensure CT PT Metering Panel  Cable Laying as per Approved drawing ",
  "Make sure the trench/openings provided for HT cable Covered and Cable Marking done",
  "Lay and connect the control cables as per ICS.",
  "Installation of HT Insulation  mat as per IEC standard",
  "Ensuring Cable tagging and Nomenclature  of source, Outgoing feeder and CT PT Metering Panel Marking",
  "Ensuring  Availability of Fire fighting equipment as per Safety Regulation.",
  "Check for Vermin  Proofing and Opening to be close.",
  "Ensure Housekeeping of CT PT Metering Panel  Internal and External Area",
  "Clear the equipment for Testing",
];
// ACDB ACTIVITY DATA
List acdb_activity_data = [
  "Unpacking ofACDB Panel at site",
  "Check for Physical Damage ",
  "Check for Outage Gadgets like LED Indication , Meter,switch, Handle",
  "Check for Record of ACDB Sr No, Make and year of Manufacturing",
  "Check the ACDB foundation as per approved  drawing.",
  "Lifting / shifting of ACDB as per OEM Guideline to avoid Damage",
  "Install the ACDB on foundation with the help of crane or shift it manually on the foundation if crane approach is not available (Indoor). Ensure that the ACDB sides are as per approved drawing.",
  "Check level of the entire channel/base frame provided for ACDB Panels before installation",
  "Position ACDB as per the drawing for clearances .",
  "Fix the anchor points with anchor fasteners",
  "ACDB generally comes in pieces, after placing on the channel assemble in one piece as per the OEM guideline.",
  "Earth pit preparation and Testing of Earth pit and Record the value for ACDB",
  "Provide earthing from two different earthing grids to panels by 50x6 GI. Busbar.",
  "Identification & Nomenclature of ACDB Earth pit ",
  "Connect earth bus for RMU/LT at two points with 50x6 mm GI strip (one with grid & other directly to earth pit). ",
  "Tightness check for all the component of ACDB Panel Like Busbar,Power/Control circuit,All Installed Component",
  "Ensure ACDB LT Cable Laying as per Approved drawing ",
  "Make sure the trench/openings provided for LT cable Covered and Cable Marking done",
  "Lay and connect the control cables as per ICS.",
  "Installation of LT Insulation  mat as per IEC standard",
  "Ensuring Cable tagging and Nomenclature  of source, Outgoing feeder and ACDB Marking",
  "Ensuring  Availability of Fire fighting equipment as per Safety Regulation.",
  "Check for Vermin  Proofing and Opening to be close.",
  "Ensure Housekeeping of ACDB  Internal and External Area",
  "Clear the equipment for Testing",
];
// CI ACTIVITY DATA
List ci_activity_data = [
  "CHECK THE SIZE, WIDTH, DEPT OF TRENCH AS PER ENGINEERING DRAWING",
  "CHECK THE BASE OF TRENCH ( ANY STONE,CONCRETE ETC) CABLE JACK/SPINDLE",
  "CHECK CABLE LAYING ROUTE IS CLEAR",
  "POSITION & ALIGNMENT CABLE OF JACK SPINDLE",
  "CONFIRM AVAILABILITY OF CABLE SCHEDULE",
  "CONFIRMATION OF CABLE LENGTH TO FRO SOURCE",
  "CUSHION OF SAND",
  "CABLE LAYING",
  "SPACING BETWEEN CABLE WITH  BRICK",
  "CABLE IDENTIFICATION TAG AFTER EVERY 5 M",
  "CUSHION OF SAND",
  "POSTING OF PROTECTION TILES",
  "PROPER LAYING PRCEEDURE ADOPTED CABLE JACK,CABLE ROLLER",
];
// CDI   ACTIVITY DATA
List cdi_activity_data = [
  "PHYSICAL INSPECTION OF CABLE DRUM NO",
  "ROLL",
  "SIZE",
  "PROPER DISMANTALING OF CABLE DRUM WODEN PLANKS",
  "INITIAL INSULATION TEST BEFORE LAYING",
  "INSULATION TEST FOR EVERY CABLE LENGTH AFTER LAYING.",
];
// MSP   ACTIVITY DATA
List msp_activity_data = [
  "UN PACKING THE MCCB PANEL",
  "CHECK INSIDE - KEYS / MANUAL",
  "PHYSICAL CHECK DAMAGE",
  "CHECK OUTER GADGETS LED/METER/SWITCH HANDLE,SELECTOR SWITCH.",
  "CHECK FOR ANY DAMAGE INSIDE PANEL,MCCB,BUS BAR ,INSULATORS,CONNECTORS.",
  "CHECK PANEL BASE FRAME ALIGNMENT & PROPER SECURE WITH NUTBOLTS",
  "CONFIRMATION FOR DOUBLE EARTHING",
  "CHECK FOR VERMING PROOFING AND OPENING TO BE CLOSE",
  "CHECK FOR MANAUL OPERATION OF MCB",
  "PROVISION  FOR LOTO  ARRANGEMENT FOR PANEL ",
  "CHECK FOR CABLE ENTRY INSIDE PANEL AND NO DAMGE  TO CABLE ",
  "CONDITION OF CABLE GLAND",
  "PROPER SUPPORT TO CABLE",
  "INSULATION TEST BEFORE CHARGING PANEL ALONG WITH CABLE",
  "PROVIDE INPUT SUPPLY 3PN+ PROPER EARTH.",
  "AFTER SUPPLY CHECK ALL FUNCTIOING OF GADGETS LED/METERS FUNCTIONS METER/VOLTMETER AND AMMETER ",
  "VOLTAGE READING",
  "BETWEEN R-Y PHASE:",
  "BETWEEN Y-B PHASE:",
  "BETWEEN B-R PHASE:",
  "BETWEEN R-N PHASE:",
  "BETWEEN Y-N PHASE:",
  "BETWEEN B-N PHASE:"
];
// CHARGER   ACTIVITY DATA
List charger_activity_data = [
  "UN PACKING THE CHARGER PANEL",
  "CHECK INSIDE - KEYS / MANUAL",
  "CHECK FOE  PHYSICAL DAMAGE",
  "CHECK OUTER GADGETS LED/METER/SWITCH HANDLE,SELECTOR SWITCH.",
  "CHECK FOR ANY DAMAGE INSIDE PANEL,MCCB,BUS BAR ,INSULATORS,CONNECTORS.",
  "CHECK CHARGER BASE FRAME ALIGNMENT & PROPER SECURE WITH NUT BOLTS.FOLLOW OEM GUIDELINE ",
  "CONFIRMATION FOR DOUBLE EARTHING",
  "CHECK FOR VERMING PROOFING AND OPENING TO BE CLOSE",
  "CHECK FOR MANAUL OPERATION OF MCCB /ELCB",
  "CHECK FOR CABLE ENTRY INSIDE PANEL AND NO DAMGE  TO CABLE",
  "CONDITION OF CABLE GLAND",
  "PROPER SUPPORT TO CABLE",
  "INSULATION TEST BEFORE CHARGING PANEL ALONG WITH CABLE",
  "PROVIDE INPUT SUPPLY 3PN+ PROPER EARTH IN PRESENCE OF CHARGER OEM",
  "AFTER SUPPLY CHECK ALL FUNCTIOING OF GADGETS LED/METERS FUNCTIONS METER/VOLTMETER AND AMMETER ",
  "BETWEEN R-Y PHASE: ",
  "BETWEEN Y-B PHASE:",
  "BETWEEN B-R PHASE:",
  "BETWEEN R-N PHASE:",
  "BETWEEN Y-N PHASE:",
  "BETWEEN B-N PHASE:",
];
// EARTH PIT ACTIVITY DATA
List earth_pit_activity_data = [
  "Unpacking of Earth pit material at site",
  "Check for Physical Damage to Earth pit Material ",
  "Check for Record of Earthing Material , Make and year of Manufacturing",
  "Check Availability of  EARTH PIT  Engineering drawing at site",
  "Ensure Earth pit depth, bore Dia and Chemical use as per OEM guidance",
  "Ensure distance between two erath pit should be more than 3 meter  and Pit Location as per Approved Engg. Drawing",
  "Ensure Earth Pit Covering with cap and Nomenclature  of pit Number",
  "Check for Earth grid Connection",
  "Identification & Nomenclature of Earth pit ",
  "Ensure Housekeeping of Earth pit External Area",
  "Clear the Earth pit for Testing  after  Proper Retention Time as per OEM Guideline",
  "Earth pit preparation and Testing of Earth pit and Record the value",
  "ENSURE CHARGER EARTHING IS SEPRATE FROM LA /STRUCTURE GROUNDING",
  "EARTH PIT NO-1",
  "EARTH PIT NO-2",
  "EARTH PIT NO-3",
  "EARTH PIT NO-4",
  "EARTH PIT NO-5",
  "EARTH PIT NO-6",
  "EARTH PIT NO-7",
  "EARTH PIT NO-8",
  "EARTH PIT NO-9",
  "EARTH PIT NO-10",
  "EARTH PIT NO-11",
  "EARTH PIT NO-12",
  "CHARGING SHED LA 1",
  "CHARGING SHED LA 2",
];

// ------------------------------------- CIVIL ENGINEERING DATA -------------------------------------

// EXCAVATION ACTIVITY DATA
List civil_exc_activity_data = [
  "Excavation drawings available on site",
  "Setting out done as specified and checked for accuracy",
  "All excavated levels along with original ground level recorded",
  "Founding Level as per drawing achieved and recorded.",
  "SBC checked as per drawing",
  "Dewatering completed",
  "Under ground utilities removed / shifted",
  "Shoring completed",
  "Access provided as per Safety Standards",
  "CAT tool Used before excavation",
  "Trial Pit taken as per standard procedure",
  "Any other points",
  "Excavated earth disposed / stacked as per safety standards",
  "Blasting operation carried out with precautions as Specified",
  "Any other Concerns",
];

// BACKFILLING ACTIVITY DATA
List civil_bf_activity_data = [
  "Were Curing & Concrete Strength requirement achieved?",
  "Were  the Surface Defects, if any, repaired / rectified and accepted?",
  "Was the Backfill Material tested and approved for filling?",
  "Were the tie rods cuts and surface repaired?",
  "Was the Concrete Surface Painted before filling?",
  "Were the foundation bolts protected?",
  "Is capacity/calibration of compaction equipment checked?",
  "Is the hydro testing done on Water Retaining Structures?",
  "Was the permissible layer(s) height marked on the structure clearly?",
  "Was the previous layer Density checked and results recorded in Lab form? ",
  "Is the present Layer Material free from roots, organic matter and any other foreign material etc?",
  "No Loose, Segregation of material and Moisture Content is visually uniform?",
  "Is the Area uniform and compacted properly including edges?",
  "Is the Compacted Layer Checked as per Specifications?",
  "In-Situ Density checked & accepted Ref. Lab form No:",
  "Cleared to proceed with the next layer",
];

// BRICK & BLOCK MASSONARY ACTIVITY DATA
List civil_mass_activity_data = [
  "Cement Material Test Certificate checked.",
  "Approved Brand & quality of bricks and blocks checked",
  "quality of Sand, Water & Water Proof Chemical Checked",
  "Wall ties, reinforcement, flashing checked",
  "Bricks / Blocks are in wet condition when used.",
  "Hacking / Rendering of Parent / Concrete surfaces done.",
  "Tie-ins anchoring, fixtures etc checked as per drg.",
  "Mortar Mix proportion Checked as per Drawing & BOQ (1:3, 1:4, 1:5 & 1:6) ",
  "Thickness of Massonary checked as per drawing",
  "Alignment / Plumb of bricks and blocks checked & found as per drawing",
  "Mortar joints uniformly struck or tooled.",
  "Transoms and Mullions checked as per drawing / spec.",
  "Inserts, embedment’s, openings, Joint  between Brick work & soffit of beam / slab properly filled.	",
  "Pointing to masonry work (if applicable) done.",
  "Expansion joints in masonry work filled / treated.",
  "Curing is done up to specified period",
];

// BLDG DOORS, WINDOWS, HARDWARE, GLAZING ACTIVITY DATA
List civil_dwg_activity_data = [
  "Approved Make/dimensions/model/material/color checked",
  "Door Frames Painted / Anodized / Powder coated",
  "Coal tar coat is applied on embedded portions ",
  "Hardware – Aluminum / Brass / C. P. Brass, SS,MS checked ",
  "Door glass & putty, beading, gasket, sealant, mastic. ",
  "Electrical components for power operated doors Checked",
  "Guides and panel sections for telescopic  doors checked",
  "General operation of doors satisfactory",
  "Frames anchored plumb and leveled satisfactory.",
  "Doors/sashes not inhibited or bound from normal movement",
  "Hardware installation is correct",
  "Glass well bedded and putty neatly trimmed / rubber / PVC beads continuous",
  "Telescopic door guides installed, secured & aligned.",
  "Operation of overhead or telescopic doors (Controls, smoothness and speed) checked and okay",
  "Hardware in good mechanical operation       ",
  "Doors are polished or painted watertight",
  "Gaps between frames & masonry / plaster properly filled by sealant (where specified)",
  "Mastic filling for composite doors Checked",
];

// FALSE CEILING ACTIVITY DATA
List civil_fc_activity_data = [
  "Nature / make / model / color / size & brand checked and procured from approved vendor",
  "Ceiling Board – AC Sheet / Gypsum / Perforated checked and MTC Reviewed.",
  "Type of support (concrete, structural steel work) checked and accepted",
  "Joint cover strips checked",
  "Suspension System / Exposed metal ‘T’ system found approved & OK",
  "Approval of framing layout based on Elect. / Mech. Requirements verified and Approved Drawings.",
  "Completion of work above the ceiling prior to start of work",
  "Suspension System e.g. set level & square prior to installation of ceiling board",
  "Ceiling board / sheets fixed correctly checked as per mnfr.",
  "Adoption for recessed lighting fixtures / A.C. Grills / Sprinklers checked & found okay",
  "Plaster boards are jointed together as per Mnfr. Spec",
  "Tightness of joints checked found satisfactory   ",
  "Overlap width checked and found as per drawing",
  "Cut boards at ceiling line checked",
  "Boards free of discoloration or damage checked",
  "Overall System alignment & cleaning checked.",
];

// FLOORING & TILING ACTIVITY DATA
List civil_ft_activity_data = [
  "as the Materials to be used in Flooring Tested and Approved with MTC?",
  "pproved type,color & shade of tiles to be checked as per spec / approved palette.",
  "routing Material or Cement verified w.r.t. specifications",
  "pproved jointing pattern reviewed & same followed.",
  "nspection of substrate bed done & found as per drawing. ",
  "pplication procedure reviewed & found as per drg. / spec.",
  "ortar Mix proportion Checked as per specifications ",
  "rout procedure, pointing, Polishing, Finishing found OK. Tile face plumb & right angles checked & found OK",
  "racks, misalignment, hollowness in bedding - Y / N",
  "rout joints observed uniform.",
  "roper slope of floor checked with water flooding and ensured that there is no water stagnant",
  "leanliness upon completion is checked",
];

// GROUTING INSPECTION ACTIVITY DATA
List civil_gi_activity_data = [
  "Grout Materials tested and approved",
  "Grout Trials carried out and Design Grout Mix approved    ",
  "Grouting Equipment/Instruments are adequate and are in working condition",
  "Pressure Gauges are calibrated",
  "Parent Concrete strength achieved as per Drawing",
  "Grout Pump/ Hose/ Guages are checked for any chokage etc. prior to Grouting",
  "Grout Hole / surface cleaned properly/Flushed with water prior to Grouting",
  "Water Tightness of Formwork Checked & found Ok",
  "Pressure Gauge is being monitored during Grouting Process to control the max.allowable pressure",
  "Grout Materials are being mixed in designed proportion and Temp. is within permissible range",
  "No. of Grout Cubes taken and Identification",
  "Consumption of Grout Mix: Theoretical",
  "Curing done upto specified period",
  "Final alignment of bolts / structure assured.",
];

// IRONITE FLORRING ACTIVITY DATA
List civil_if_activity_data = [
  "Was the Materials to be used in Flooring Tested and Approved with MTC?",
  "Approved type of chemicals / hardner to be checked as per spec / approved methodology.",
  "Brand and quality parameters of Grouting Material or Cement verified w.r.t. specifications.",
  "Brand, Sizes & Quality of glass strip verified as per Specifications/ Drawings",
  "Approved methodology adopted & same followed.",
  "Inspection of substrate bed done & found as per drawing.",
  "Application procedure reviewed & found as per drg. / spec.",
  "Mortar Mix proportion Checked as per specifications ",
  "Grout procedure, pointing, Polishing, Line, Level, Slope and Finishing found OK.",
  "Fixing of glass strip and gap to be maintained has checked & found OK",
  "Cracks, misalignment, hollowness in bedding - Y / N",
  "Grout joints observed uniform.",
  "Proper slope of floor checked with water flooding and ensured that there is no water stagnant",
  "Cleanliness upon completion is checked",
];

// PAINTING ACTIVITY DATA
List civil_painting_activity_data = [
  "Approved brand, shade & quality of paints verified to MTC",
  "Approved brand of POP,Putty,primer & finishing checked",
  "Manufacturer’s data sheet reviewed",
  "Date of manufacture, pot or shelf life on containers and sealing of containers verified & found okay",
  "Anti-fungus material, if applicable checked",
  "Storage conditions checked & found protected                                           ",
  "Surface preparation, sand blasting, Scrubbing where Applicable checked and found satisfactory ",
  "Application procedure reviewed & found as per spec.",
  "POP, Putty applied as per specifications ",
  "Number of coats with primer applied as per drg. / spec.",
  "Time lag between each coat ensured and maintained as per spec.",
  "Thickness of dry film checked and found as per spec.",
  "Evenness of applied coats checked and found OK",
  "Brush marks, sags, runs etc checked and found OK",
  "Plaster Repairing / Grout joints observed uniform ",
  "Cleanliness of area upon completion – doors, windows, floor observed satisfactory.",
  "Guarantee bond taken as per BOQ.",
];

// PAVING ACTIVITY DATA
List civil_paving_activity_data = [
  "Type and color of Pavers,  manufacturer checked and procured from approved vendor ",
  "Testing of Pavers (MTC and Test Report) verified",
  "Binding Material Checked and confirmed specifications",
  "Jointing pattern approved – Y / N verified",
  "Surface Prepared as per drawing / specifications",
  "Line and top levels marked",
  "Compaction of under layer checked",
  "Line, level, undulations checked & rectified (if any)   ",
  "Cracks, misalignment, hollowness in bedding ",
  "Filling of joints uniform",
  "Cleaning of Surface",
];

// WALL CLADDING & ROOFING ACTIVITY DATA
List civil_wcr_activity_data = [
  "Correct cladding or roofing profile  / gauge / coating procured from approved vendor ",
  "Material inspected physically & reviewed with MTC",
  "Fasteners, flashing, closer strips and caulking   ",
  "Proper tools for installation checked",
  "Wall insulation / Roof Insulation mat. approved",
  "Color, External coating, internal coating & Condition before installation checked",
  "Line, level & overlaps of sheets checked",
  "Correct spacing of fasteners done",
  "Insulation, Painting done on framed supports",
  "Supports for roof insulation are Fixed",
  "Placement of closer strips checked & found as per drg.",
  "Flashing, Bolting or welding done as per specifications",
  "Alignment of seams and fasteners found okay ",
  "Tightness of joints / fasteners observed satisfactory",
  "Damaged parts – repaired / replaced",
  "Water tightness test done & found no leakage",
  "Roofing slope & alignment checked as per spec.",
  "Joint alignment & filling with approved material ensured.",
  "Cutout Size and Locations as per Drawing",
];

// WATER PROOFING ACTIVITY DATA
List civil_wp_activity_data = [
  "Approved vendor &  brand verified as per specifications",
  "Type of water proofing like brick bat coba / bituminous felt type / elastomeric polyurethane based checked ",
  "Manufacturer’s data and MTC reviewed",
  "Expiry date on containers / bags checked & okay.",
  "Storage conditions checked & found protected                                            ",
  "Surface preparation like cleaning, hacking&joints checked",
  "Application procedure reviewed & found as per spec.",
  "Mix proportions verified as per manufacturer guidelines",
  "Primer applied & checked as per manufacturer guidelines",
  "Mortar layer / slurry applied as per specifications",
  "Coats, laps and thickness checked & found as per spec.",
  "Drain pipes / bell mouths installed ",
  "Jointing & Orientation of layers as per specifications",
  "Slope of finished surface checked and found OK",
  "Water-proofing thickness, dimensions checked and OK",
  "Curing, Cracks, misalignment, hollowness checked",
  "Water Leakage Testing done & found OK and Guarantee bond taken as per BOQ",
];
