import 'package:intl/intl.dart';

import '../model/employee.dart';

String dmy = DateFormat('dd-MM-yyyy').format(DateTime.now());

List<dynamic> keySrno = [
  'A1',
  '1',
  'A2',
  '1',
  '2',
  '3',
  'A3',
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  'A4',
  '1',
  '2',
  '3',
  '4',
  'A5',
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  'A6',
  '1',
  '2',
  '3',
  'A7',
  '1',
  '2',
  '3',
  '4',
  '5',
  'A8',
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '10',
  '11',
  '12',
  '13',
  '14',
  '15',
  '16',
  '17',
  '18',
  '19',
  '20',
  '21',
  '22',
  '23',
  '24',
  '25',
  'A9',
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '10',
  '11',
  'A10',
  '1',
  '2',
  '3',
];
List keyEvents = [
  'TML contract Award',
  'Letter of Award reveived from TML',
  'Site Survey, Job scope finalization and Proposed layout submission',
  'Initial survey of Depot with TML & STA Team',
  'Details survey of Depot with TPC Civil & Elecrical team including Soil testing',
  '   Survey Report submission with Existing & Proposed Layout Drawings',
  'Detailed Engineering for Approval of Civil & Electrical Layout, GA Drawing from TML',
  'Preparation of Drawings of Civil Activities (Laypout,foundation, charging Bay & shed Aux. facilities)',
  'Preparation of EV Layout Drawings of Electrical Activities (SLD, cable laying)',
  'Preparation of Shed Lighting Drawings & Specification',
  'Authority Approval for Depot Layout Drawing',
  'Job scope finalization & preparation of BOQ',
  'TML Approval for BOQ (Civil & Electical) ',
  'Initial Approval of statutory clearances for EV Bus Depot',
  'Consent to Established-Pollution control board approval',
  'Charging Shed Erection Approval',
  'Fire NOC for Electrical vehicle charging infrastructure',
  'Power Connection/ load applied by STA to Discom',
  'Tender & L1 Vendor Finalisation',
  'Placement of PR/PO for PSS & RMU',
  'Placement of PR/PO for Charger',
  'Placement of PR/PO for SFU Panel',
  'Placement of PR/PO for HT Cable',
  'Placement of PR/PO for LT Cable',
  'Placement of PR/PO for services Civil work',
  'Placement of PR/PO for services Electrical work',
  'Engg. Drawing Submission of equipment by OEM',
  'Approval of Engg Drawing & manufacture clearence',
  'Resource Mobalization activity',
  'Deployment of Civil Man Power',
  'Deployment of Electrical Man Power',
  'Estabilisment of Site Project office',
  'Receipt of all Materials at Site',
  'Delivery of PSS & RMU at Site',
  'Delivery of Charger at Site',
  'Delivery of SFU Panel at Site',
  'Delivery of HT Cable at Site',
  'Delivery of LT Cable at Site',
  'Civil Active Infra Development completed at Bus Depot',
  'Concrete breaking',
  'Manual Excavation',
  'Soling',
  'PCC & Curing',
  'Reinforcement tying of Raft (charger Foundation)',
  'Shuttering of Raft (charger Foundation)',
  'Concreting of Raft (charger Foundation) and Curing',
  'Reinforcement tying of pedestal (PSS)',
  'Shuttering of pedestal (PSS Foundation)',
  'Concreting of pedestal (PSS Foundation)',
  'Reinforcement tying of Raft (shed)',
  'Shuttering of Raft (shed)',
  'Concreting of Raft (shed) and Curing',
  'Backfilling',
  'Erection of shed structure ( Traditional Shed )',
  'Roof sheeting',
  'Concreting around excavated area',
  'Thermoplastic paint',
  'Crash barrier',
  '5S activity',
  'Cable Trenching (for burried cable)',
  'Compressor foundation and room',
  'DTB Room',
  'Road leveling and resurfacing',
  'Painiting',
  'Electrical Infra Development completed at Bus Depot',
  'Earthing Pit erection with GI Flat',
  'Installation of PSS & RMU',
  'Installation of Charger',
  'Installation of SFU Panel',
  'Laying of HT cable Erection',
  ' Laying of LT cable Erection',
  'Installation of VTPN/SPN DB',
  'Installation of Shed Lighting & other arrangement',
  ' LA Arrangement with GI Flat on charging Shed',
  'Commissioning & Testing of Bus Depot Electrical Infa',
  'EI Approval for Electrical Equipment',
  'Bus Depot Active Infra work Completed',
  'CMS Integration',
  'Bus Depot work Completed & Handover to TML',
  'EV Bus Charging Active Infra Completed',

  // 'Letter of Award reveived  from TML',
  // 'Letter of Intent reveived  from TML',
  // 'Site Survey, Job scope finalization  and final layout preparation',
  // 'Initial survey of Depot with TML & STA Team',
  // 'Details  survey of Depot with TPC Civil & Elecrical team',
  // 'Survey Report submission with Existing & Proposed Layout  Drawings',
  // 'Job scope finalization & preparation of BOQ',
  // 'Power Connection/ load applied by STA to Discom',
  // 'Detailed Engineering for Approval of  Civil & Electrical  Layout, GA Drawing from TML',
  // 'RFC Drawings of Civil Activities',
  // 'EV Layout Drawings of Electrical Activities',
  // 'Shed Lighting Drawings & Specification',
  // 'Site Mobalization activity Completed',
  // 'Deployment of  Civil Man Power',
  // 'Deployment of  Electrical Man Power',
  // 'Estabilisment of Site Project office',
  // 'Approval of statutory clearances of BUS Depot',
  // 'Consent to Established-Pollution control board approval',
  // 'Consent to Operate-Pollution control board approval',
  // 'Fire NOC  for Electrical vehicle charging infrastructure',
  // 'Chief Inspector of Factory /Director(DISH Approval)',
  // 'CEIG/EI Approval',
  // 'Charging Shed Errection Approval',
  // 'Effluent treatment plant',
  // 'Soild Waste Managent',
  // 'ETP Plant ',
  // 'Hazardous waste approval ',
  // 'Procurement of Order Finalisation Completed',
  // 'PR/PO Generation for  PSS',
  // 'PR/PO Generation for Charger',
  // 'PR/PO Generation for SFU Panel',
  // 'PR/PO Generation for HT Cable',
  // 'PR/PO Generation for LT Cable',
  // 'Receipt of all Materials at Site',
  // 'Delivery of PSS at Site',
  // 'Delivery of Charger at Site',
  // 'Delivery of SFU Panel at Site',
  // 'Delivery of HT Cable at Site',
  // 'Delivery of  LT Cable at Site',
  // 'Civil Infra Development completed at Bus Depot',
  // 'Concrete breaking',
  // 'Manual Excavation',
  // 'Soling',
  // 'PCC & Curing',
  // 'Reinforcement tying of Raft (charger Foundation)',
  // 'Shuttering of Raft (charger Foundation)',
  // 'Concreting of Raft (charger Foundation) and Curing',
  // 'Reinforcement tying of pedestal (PSS)',
  // 'Shuttering of pedestal (PSS Foundation)',
  // 'Concreting of pedestal (PSS Foundation)',
  // 'Reinforcement tying of Raft (shed)',
  // 'Shuttering of Raft (shed)',
  // 'Concreting of Raft (shed) and Curing',
  // 'Backfilling',
  // 'Erection of shed structure',
  // 'Roof sheeting',
  // 'Concreting around excavated area',
  // 'Thermoplastic paint',
  // 'Crash barrier',
  // '5S activity',
  // 'Cable Trenching (for burried cable)',
  // 'Compressor foundation and room',
  // 'DTB Room',
  // 'Road leveling and resurfacing',
  // 'Painiting ',
  // 'Electrical Infra Development completed at Bus Depot',
  // 'Earthing Pit erection with GI Flat',
  // 'LA Arrangement with GI Flat on charging Shed',
  // 'Installation of PSS',
  // 'Installation of Charger',
  // 'Installation of SFU Panel',
  // 'Laying of HT  cable Erection',
  // 'Laying of LT cable Erection',
  // 'Installation of VTPN/SPN DB',
  // 'Installation of Shed Lighting & other  arrangement',
  // 'Commissioning & Testing  of Bus Depot',
  // 'Bus Depot work Completed',
  // 'CMS Integration',
  // 'Bus Depot work Completed & Handover to TML',
];
List<String> startDate = [
  '21-06-2023',
  '21-06-2023',
  '22-06-2023',
  '22-06-2023',
  '23-06-2023',
  '13-07-2023',
  '20-07-2023',
  '20-07-2023',
  '04-08-2023',
  '07-08-2023',
  '09-08-2023',
  '16-08-2023',
  '19-08-2023',
  '30-07-2023',
  '30-07-2023',
  '30-07-2023',
  '19-08-2023',
  '19-08-2023',
  '20-07-2023',
  '20-07-2023',
  '20-07-2023',
  '20-07-2023',
  '20-07-2023',
  '20-07-2023',
  '26-08-2023',
  '26-08-2023',
  '25-07-2023',
  '04-08-2023',
  '05-09-2023',
  '05-09-2023',
  '05-09-2023',
  '05-09-2023',
  '30-07-2023',
  '30-07-2023',
  '30-07-2023',
  '30-07-2023',
  '30-07-2023',
  '30-07-2023',
  '10-09-2023',
  '10-09-2023',
  '16-09-2023',
  '22-09-2023',
  '25-09-2023',
  '27-09-2023',
  '07-10-2023',
  '14-10-2023',
  '09-10-2023',
  '17-10-2023',
  '24-10-2023',
  '14-10-2023',
  '26-10-2023',
  '26-10-2023',
  '04-11-2023',
  '06-11-2023',
  '01-12-2023',
  '09-12-2023',
  '18-12-2023',
  '18-12-2023',
  '25-12-2023',
  '09-12-2023',
  '04-11-2023',
  '04-11-2023',
  '29-11-2023',
  '19-12-2023',
  '02-10-2023',
  '02-10-2023',
  '18-12-2023',
  '28-10-2023',
  '23-10-2023',
  '11-11-2023',
  '12-10-2023',
  '12-10-2023',
  '12-10-2023',
  '17-11-2023',
  '22-12-2023',
  '26-12-2023',
  '28-12-2023',
  '28-12-2023',
  '28-12-2023',
  '06-01-2024',
];
List<String> endDate = [
  '21-06-2023',
  '21-06-2023',
  '19-07-2023',
  '22-06-2023',
  '12-07-2023',
  '19-07-2023',
  '25-08-2023',
  '29-07-2023',
  '08-08-2023',
  '08-08-2023',
  '15-08-2023',
  '18-08-2023',
  '25-08-2023',
  '16-11-2023',
  '18-08-2023',
  '18-08-2023',
  '16-11-2023',
  '17-09-2023',
  '04-09-2023',
  '29-07-2023',
  '29-07-2023',
  '29-07-2023',
  '29-07-2023',
  '29-07-2023',
  '04-09-2023',
  '04-09-2023',
  '03-08-2023',
  '08-08-2023',
  '14-09-2023',
  '11-09-2023',
  '11-09-2023',
  '14-09-2023',
  '17-12-2023',
  '17-12-2023',
  '27-10-2023',
  '22-09-2023',
  '10-11-2023',
  '11-10-2023',
  '27-12-2023',
  '15-09-2023',
  '21-09-2023',
  '24-09-2023',
  '03-10-2023',
  '08-10-2023',
  '13-10-2023',
  '22-10-2023',
  '16-10-2023',
  '23-10-2023',
  '01-11-2023',
  '25-10-2023',
  '29-10-2023',
  '03-11-2023',
  '05-11-2023',
  '30-11-2023',
  '08-12-2023',
  '17-12-2023',
  '21-12-2023',
  '26-12-2023',
  '27-12-2023',
  '16-12-2023',
  '23-11-2023',
  '28-11-2023',
  '18-12-2023',
  '27-12-2023',
  '27-12-2023',
  '11-10-2023',
  '21-12-2023',
  '03-11-2023',
  '29-10-2023',
  '20-11-2023',
  '20-10-2023',
  '13-10-2023',
  '14-10-2023',
  '18-11-2023',
  '25-12-2023',
  '27-12-2023',
  '06-01-2024',
  '31-12-2023',
  '06-01-2024',
  '06-01-2024',
];

List<dynamic> weightage = [
  0.00,
  0.00,
  2.50,
  1.00,
  1.00,
  0.50,
  2.50,
  1.00,
  0.25,
  0.10,
  0.40,
  0.30,
  0.45,
  10.00,
  3.00,
  2.00,
  2.00,
  3.00,
  15.00,
  2.00,
  2.00,
  2.00,
  2.00,
  2.00,
  1.00,
  1.00,
  1.00,
  2.00,
  5.00,
  1.25,
  1.25,
  2.50,
  15.00,
  5.00,
  3.00,
  2.00,
  3.00,
  2.00,
  30.00,
  2.50,
  0.90,
  1.00,
  1.50,
  1.50,
  1.50,
  1.50,
  1.50,
  1.50,
  6.50,
  0.60,
  0.60,
  0.60,
  1.00,
  1.20,
  1.00,
  0.60,
  0.30,
  0.30,
  0.30,
  1.00,
  0.50,
  1.00,
  0.80,
  0.30,
  15.00,
  1.00,
  1.50,
  1.00,
  0.50,
  1.50,
  4.00,
  1.50,
  1.00,
  1.00,
  1.00,
  1.00,
  5.00,
  0.50,
  4.00,
  0.50,
];
List<Employee> getKeyEventsData() {
  List<Employee> list = [];
  for (var i = 0; i < keyEvents.length; i++) {
    print(weightage.length);
    list.add(
      Employee(
        srNo: keySrno[i],
        activity: keyEvents[i],
        originalDuration: 1,
        startDate: startDate[i],
        // DateFormat('dd-MM-yyyy').format(DateTime.parse(startDate[i])),
        endDate: endDate[i],
        actualstartDate: dmy,
        actualendDate: dmy,
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: weightage[i],
      ),
    );
  }
  return list;

//   for(int i=0 ; i< 90 ; i++){
//  return [
//     Employee(
//       srNo: 'A1',
//       activity: keyEvents[0],
//       originalDuration: 1,
//       startDate: dmy,
//       endDate: dmy,
//       actualstartDate: dmy,
//       actualendDate: dmy,
//       actualDuration: 0,
//       delay: 0,
//       reasonDelay: '',
//       unit: 0,
//       scope: 0,
//       qtyExecuted: 0,
//       balanceQty: 0,
//       percProgress: 0,
//       weightage: 0.5,
//     ),
//  ];
//   }

  // Employee(
  //   srNo: 1,
  //   activity: keyEvents[1],
  //   originalDuration: 1,
  //   startDate: dmy,
  //   endDate: dmy,
  //   actualstartDate: dmy,
  //   actualendDate: dmy,
  //   actualDuration: 0,
  //   delay: 0,
  //   reasonDelay: '',
  //   unit: 0,
  //   scope: 0,
  //   qtyExecuted: 0,
  //   balanceQty: 0,
  //   percProgress: 0,
  //   weightage: 0.5,
  // ),
  // Employee(
  //   srNo: 'A2',
  //   activity: keyEvents[2],
  //   originalDuration: 1,
  //   startDate: dmy,
  //   endDate: dmy,
  //   actualstartDate: dmy,
  //   actualendDate: dmy,
  //   actualDuration: 0,
  //   delay: 0,
  //   reasonDelay: '',
  //   unit: 0,
  //   scope: 0,
  //   qtyExecuted: 0,
  //   balanceQty: 0,
  //   percProgress: 0,
  //   weightage: 0.5,
  // ),
  // Employee(
  //   srNo: 1,
  //   activity: keyEvents[3],
  //   originalDuration: 1,
  //   startDate: dmy,
  //   endDate: dmy,
  //   actualstartDate: dmy,
  //   actualendDate: dmy,
  //   actualDuration: 0,
  //   delay: 0,
  //   reasonDelay: '',
  //   unit: 0,
  //   scope: 0,
  //   qtyExecuted: 0,
  //   balanceQty: 0,
  //   percProgress: 0,
  //   weightage: 0.5,
  // ),
  // Employee(
  //   srNo: 2,
  //   activity: keyEvents[4],
  //   originalDuration: 1,
  //   startDate: dmy,
  //   endDate: dmy,
  //   actualstartDate: dmy,
  //   actualendDate: dmy,
  //   actualDuration: 0,
  //   delay: 0,
  //   reasonDelay: '',
  //   unit: 0,
  //   scope: 0,
  //   qtyExecuted: 0,
  //   balanceQty: 0,
  //   percProgress: 0,
  //   weightage: 0.5,
  // )
}

List<Employee> getEmployeeDataA2() {
  return [
    Employee(
      srNo: 1,
      activity: 'Initial Survey Of Depot With TML & STA Team.',
      originalDuration: 1,
      startDate: dmy,
      endDate: dmy,
      actualstartDate: dmy,
      actualendDate: dmy,
      actualDuration: 0,
      delay: 0,
      reasonDelay: '',
      unit: 0,
      scope: 0,
      qtyExecuted: 0,
      balanceQty: 0,
      percProgress: 0,
      weightage: 0.5,
    ),
    Employee(
        srNo: 2,
        activity: 'Details Survey Of Depot With TPC Civil & Electrical Team',
        originalDuration: 1,
        startDate: dmy,
        endDate: dmy,
        actualstartDate: dmy,
        actualendDate: dmy,
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 1.0),
    Employee(
        srNo: 3,
        activity:
            'Survey Report Submission With Existing & Proposed Layout Drawings.',
        originalDuration: 1,
        startDate: dmy,
        endDate: dmy,
        actualstartDate: dmy,
        actualendDate: dmy,
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 0.3),
    Employee(
        srNo: 4,
        activity: 'Job Scope Finalization & Preparation Of BOQ',
        originalDuration: 1,
        startDate: dmy,
        endDate: dmy,
        actualstartDate: dmy,
        actualendDate: dmy,
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 0.5),
    Employee(
        srNo: 5,
        activity: 'Power Connection / Load Applied By STA To Discom.',
        originalDuration: 1,
        startDate: dmy,
        endDate: dmy,
        actualstartDate: dmy,
        actualendDate: dmy,
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 0.3)
  ];
}

List<Employee> getEmployeeDataA3() {
  return [
    Employee(
        srNo: 1,
        activity: 'RFC Drawings Of Civil Activities',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 1.5),
    Employee(
        srNo: 2,
        activity: ' EV Layout Drwaings Of Electrical Activities',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 0.7),
    Employee(
        srNo: 3,
        activity: 'Shed Lighting Drawings And Specification',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 0.3),
  ];
}

List<Employee> getEmployeeDataA4() {
  return [
    Employee(
        srNo: 1,
        activity: 'Deployment of  Civil Man Power',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 1.25),
    Employee(
        srNo: 2,
        activity: ' Deployment of  Electrical Man Power',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 1.25),
    Employee(
        srNo: 3,
        activity: 'Estabilisment of Site Project office',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 2.5),
  ];
}

List<Employee> getEmployeeDataA5() {
  return [
    Employee(
      srNo: 1,
      activity: 'Consent to Established-Pollution control board approval',
      originalDuration: 1,
      startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
      endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
      actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
      actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
      actualDuration: 0,
      delay: 0,
      reasonDelay: '',
      unit: 0,
      scope: 0,
      qtyExecuted: 0,
      balanceQty: 0,
      percProgress: 0,
      weightage: 1.5,
    ),
    Employee(
        srNo: 2,
        activity: 'Consent to Operate-Pollution control board approval',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 1.5),
    Employee(
        srNo: 3,
        activity: 'Fire NOC  for Electrical vehicle charging infrastructure',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 1.5),
    Employee(
        srNo: 4,
        activity: 'Chief Inspector of Factory /Director(DISH Approval)',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 1.5),
    Employee(
        srNo: 5,
        activity: 'CEIG/EI Approval',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 1.5),
    Employee(
        srNo: 6,
        activity: 'Charging Shed Errection Approval',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 1.5),
    Employee(
        srNo: 7,
        activity: 'Effluent treatment plant',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 1.5),
    Employee(
        srNo: 8,
        activity: 'Soild Waste Managent',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 1.5),
    Employee(
        srNo: 9,
        activity: 'ETP Plant',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 1.5),
    Employee(
        srNo: 10,
        activity: 'Hazardous waste approval ',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 1.5),
  ];
}

List<Employee> getEmployeeDataA6() {
  return [
    Employee(
        srNo: 1,
        activity: 'PR/PO Generation for  PSS',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 3.0),
    Employee(
        srNo: 2,
        activity: 'PR/PO Generation for Charger',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 3.0),
    Employee(
        srNo: 3,
        activity: 'PR/PO Generation for SFU Panel',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 3.0),
    Employee(
        srNo: 4,
        activity: 'PR/PO Generation for HT Cable',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 3.0),
    Employee(
        srNo: 5,
        activity: 'PR/PO Generation for LT Cable',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 3.0)
  ];
}

List<Employee> getEmployeeDataA7() {
  return [
    Employee(
        srNo: 1,
        activity: 'Delivery of PSS at Site',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 3.3),
    Employee(
        srNo: 2,
        activity: 'Delivery of Charger at Site',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 3.3),
    Employee(
        srNo: 3,
        activity: 'Delivery of SFU Panel at Site',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 1.1),
    Employee(
        srNo: 4,
        activity: 'Delivery of HT Cable at Site',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 1.1),
    Employee(
        srNo: 5,
        activity: 'Delivery of  LT Cable at Site',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 1.1)
  ];
}

List<Employee> getEmployeeDataA8() {
  return [
    Employee(
        srNo: 1,
        activity: 'Concrete breaking ',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 2.4),
    Employee(
        srNo: 2,
        activity: 'Manual Excavation',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 0.9),
    Employee(
        srNo: 3,
        activity: 'Soling',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 1.1),
    Employee(
        srNo: 4,
        activity: 'PCC & Curing',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 1.5),
    Employee(
        srNo: 5,
        activity: 'Reinforcement tying of Raft (charger Foundation)',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 1.5),
    Employee(
        srNo: 6,
        activity: 'Shuttering of Raft (charger Foundation)',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 1.5),
    Employee(
        srNo: 7,
        activity: 'Concreting of Raft (charger Foundation) and Curing',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 1.5),
    Employee(
        srNo: 8,
        activity: 'Reinforcement tying of pedestal (PSS)',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 1.5),
    Employee(
        srNo: 9,
        activity: 'Shuttering of pedestal (PSS Foundation) ',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 1.5),
    Employee(
        srNo: 10,
        activity: 'Concreting of pedestal (PSS Foundation) ',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 6.6),
    Employee(
        srNo: 11,
        activity: 'Reinforcement tying of Raft (shed)',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 0.6),
    Employee(
        srNo: 12,
        activity: 'Shuttering of Raft (shed)',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 0.6),
    Employee(
        srNo: 13,
        activity: 'Concreting of Raft (shed) and Curing',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 0.6),
    Employee(
        srNo: 14,
        activity: 'Backfilling',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 1.1),
    Employee(
        srNo: 15,
        activity: 'Erection of shed structure',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 1.2),
    Employee(
        srNo: 16,
        activity: 'Roof sheeting',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 1.1),
    Employee(
        srNo: 17,
        activity: 'Concreting around excavated area',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 0.6),
    Employee(
        srNo: 18,
        activity: 'Thermoplastic paint',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 0.3),
    Employee(
        srNo: 19,
        activity: 'Crash barrier ',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 0.3),
    Employee(
        srNo: 20,
        activity: '5S activity',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 0.3),
    Employee(
        srNo: 21,
        activity: 'Cable Trenching (for burried cable)',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 1.0),
    Employee(
        srNo: 22,
        activity: 'Compressor foundation and room',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 0.5),
    Employee(
        srNo: 23,
        activity: 'DTB Room',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 0.5),
    Employee(
        srNo: 24,
        activity: 'Road leveling and resurfacing',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 0.8),
    Employee(
        srNo: 25,
        activity: 'Painiting ',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 0.3),
  ];
}

List<Employee> getEmployeeDataA9() {
  return [
    Employee(
        srNo: 1,
        activity: 'Earthing Pit erection with GI Flat',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 1),
    Employee(
        srNo: 2,
        activity: 'LA Arrangement with GI Flat on charging Shed',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 0.20),
    Employee(
        srNo: 3,
        activity: 'Installation of PSS',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 2.0),
    Employee(
        srNo: 4,
        activity: 'Installation of Charger',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 2.0),
    Employee(
        srNo: 5,
        activity: 'Installation of SFU Panel',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 0.50),
    Employee(
        srNo: 6,
        activity: 'Laying of HT  cable Erection',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 4),
    Employee(
        srNo: 7,
        activity: 'Laying of LT cable Erection',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 3),
    Employee(
        srNo: 8,
        activity: 'Installation of VTPN/SPN DB',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 0.5),
    Employee(
        srNo: 9,
        activity: 'Installation of Shed Lighting & other  arrangement ',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 1.0),
    Employee(
        srNo: 10,
        activity: 'Commissioning & Testing  of Bus Depot ',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 1.0)
  ];
}

List<Employee> getEmployeeData10() {
  return [
    Employee(
        srNo: 1,
        activity: 'CMS Integration',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 0.5),
    Employee(
        srNo: 2,
        activity: 'Bus Depot work Completed & Handover to TML',
        originalDuration: 1,
        startDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        endDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualstartDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualendDate: DateFormat('dd-MM-yyyy').format(DateTime.now()),
        actualDuration: 0,
        delay: 0,
        reasonDelay: '',
        unit: 0,
        scope: 0,
        qtyExecuted: 0,
        balanceQty: 0,
        percProgress: 0,
        weightage: 4.5),
  ];
}
